### ISSUE TITLE
Unhandled promise rejection is observed if an exception is thrown inside tryParseBuffer

### ISSUE THREAD

**Issue by mykola-mokhnach** [joeferner/node-bplist-parser#17]
```
(node:55502) UnhandledPromiseRejectionWarning: Error: Invalid binary plist. Expected 'bplist' at offset 0.
at exports.parseBuffer (/Users/xxx/Documents/appium-beta/node_modules/bplist-parser/bplistParser.js:55:11)
at tryParseBuffer (/Users/xxx/Documents/appium-beta/node_modules/bplist-parser/bplistParser.js:28:18)
at /Users/xxx/Documents/appium-beta/node_modules/bplist-parser/bplistParser.js:46:7
at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
(node:55502) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by mykola-mokhnach** [comment]
Issue source: https://github.com/appium/appium/issues/12970#issuecomment-520329482

**Comment by maggie5750** [comment]
@mykola-mokhnach  Any updates?

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-support/pull/128 should fix that

**Comment by maggie5750** [comment]
@mykola-mokhnach  Is this fix in appium@beta?
