### ISSUE TITLE
TypeError: callback is not a function

### ISSUE THREAD

**Issue by aluminum1** [joeferner/node-bplist-parser#23]
When I try asking Node to execute the following code:

```
const bplist = require('bplist-parser');

(async () => {

    const obj = await bplist.parseFile('my_file.bplist');

    console.log(JSON.stringify(obj));

})();
```

I get the following error message:

```
./node_modules/bplist-parser/bplistParser.js:44
        return callback(err);
               ^

TypeError: callback is not a function
    at ReadFileContext.callback (./node_modules/bplist-parser/bplistParser.js:44:16)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:261:13)
```

Not sure if it is a bug or if I'm doing something wrong.

**Comment by aluminum1** [comment]
I had garbled the file extension - it works now.
